name: Pages

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.26

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Prepare JSON schema
        run: |
          mkdir ./public/schemas
          bun create-json-schema
          mv ./dist/update.json ./public/schemas/update.json

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          wranglerVersion: "3.41.0"
          command: pages deploy ./public/ --project-name=${{ secrets.CLOUDFLARE_PAGE_NAME }} --branch=main --commit-dirty=true
